# Generated by Django 5.2.9 on 2025-12-11 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, upload_to='authors/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['second_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('isbn', models.CharField(help_text='13 символов', max_length=13, unique=True, verbose_name='ISBN')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена со скидкой')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='Издательство')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('language', models.CharField(default='Русский', max_length=50, verbose_name='Язык')),
                ('cover_type', models.CharField(choices=[('hard', 'Твёрдая'), ('soft', 'Мягкая'), ('electronic', 'Электронная')], default='soft', max_length=20, verbose_name='Тип обложки')),
                ('cover_image', models.ImageField(blank=True, upload_to='books/covers/', verbose_name='Обложка')),
                ('average_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Средний рейтинг')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Количество оценок')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='main.author', verbose_name='Автор')),
                ('categories', models.ManyToManyField(related_name='books', to='main.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='main_book_title_77196d_idx'), models.Index(fields=['isbn'], name='main_book_isbn_e3af7a_idx'), models.Index(fields=['average_rating'], name='main_book_average_900904_idx'), models.Index(fields=['price'], name='main_book_price_a6899a_idx')],
            },
        ),
    ]
